### ISSUE TITLE
QQ群819908813 人员已满

### ISSUE THREAD

**Issue by jiangminbing** [mercyblitz/tech-weekly#3]
QQ群819908813 能否建立其他分群？

**Comment by mercyblitz** [comment]
可以考虑使用钉钉群，人数更多：

“Apache Dubbo开源讨论群”群的钉钉群号： 21973601
“Spring Cloud Alibaba 开源讨论群”群的钉钉群号： 21914947
“Nacos社区群”群的钉钉群号： 21708933
“Sentinel开源讨论群”群的钉钉群号： 21977771

**Comment by hxgqh** [comment]
几个群都满了。。。

**Comment by marstalk** [comment]
@mercyblitz 群满了
